# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about_group"
  weight = 10

[[main]]
  name = "Research"
  url = "#research"
  weight = 20

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 30

[[main]]
  name = "Blogs"
  url = "#posts"
  weight = 40

[[main]]
  name = "News"
  url = "#talk"
  weight = 50

[[main]]
  name = "Softwares"
  url = "#projects"
  weight = 60

[[main]]
  name = "People"
  url = "#people"
  weight = 70

[[main]]
  name = "Openings"
  url = "#openings"
  weight = 80

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
